# Generated by Django 3.2 on 2021-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='added_date',
        ),
        migrations.AddField(
            model_name='project',
            name='added_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
